# -*- coding: utf-8 -*-
"""ex6-option-XXXXXXXX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14sSI4TUV-BIg48313rkxDM797IVu0VqP

- ファイル名のXXXXXXXXのところは学籍番号に変更してください
- プログラム中にstudent_numberに自分の学籍番号を入れてください
"""

student_number = 62101046

"""提出の必要はありません

オプション課題: 数字ピラミッド
以下の仕様を満たすような数字のピラミッドをprintする関数pyramid_numを作成せよ
- ピラミッドのn段目の数字の個数はn個
- ピラミッドはn = 1から始まるとし、1段目1番目の数字は1とする
- n >= 2 段目以降において
  - n 段目のm番目の数字は、n-1段目のm-1番目の数字とm番目の数字を足したものとする
  - n-1段目のm-1番目やm番目の数字が存在しない場合は、そこは0として計算する

関数自体の仕様は以下の通りとする
- pyramid_num()の引数はint型1つとし、引数に渡した数nに応じたn段の数字のピラミッドを作成する
- ピラミッドをprintする際は、1段ごとに改行し、数字と数字は半角スペースで区切る
  - 各段の最後の数字の後ろには何もprintしてはいけないが、例外として半角スペースが1つあっても良いとする
- 引数がint型でない場合、もしくは0以下の場合は何もprintせずに終了する
- 返り値は特に気にしなくて良い

採点は関数をこちらで呼びだして行うので、関数名の間違いなどには十分注意すること

実行例:
```
> pyramid_num(6)
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1
1 5 10 10 5 1
```
"""

def pyramid_num(n):
  """数字のピラミッドを表示する関数

  Args:
    n (int): ピラミッドの行数

  Returns:
    なし
  """
  pass