# -*- coding: utf-8 -*-
"""ex6-1-XXXXXXXX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rTeeKjrZPE5NwIYRywOZWs9W63g93Yym

- ファイル名のXXXXXXXXのところは学籍番号に変更してください
- プログラム中にstudent_numberに自分の学籍番号を入れてください
"""

student_number = 62101046

"""課題1:
引数として与えられた整数のリストに対し、先頭から要素を調べ、今まで調べた要素の中で最も小さい値の場合、その値を"Find min: <値>"の形式で表示する関数 find_min() を作成せよ

ただし、リストの先頭の要素は必ず"Find min: <配列>"の形式で表示すること

実行例:
```
> find_min([3, 8, 2, 4, -1, -5, 3, -8])
Find min: 3
Find min: 2
Find min: -1
Find min: -5
Find min: -8
```
"""

def find_min(ints):
    min = ints[0] + 1
    for i in ints:
        if min > i:
            min = i
            print("Find min: " + str(min))
