# -*- coding: utf-8 -*-
"""ex3-0-XXXXXXXX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o0NGbrlu7w4wrrddFYiJR3MnYXEh5rTq

- ファイル名のXXXXXXXXのところは学籍番号に変更してください
- プログラム中にstudent_numberに自分の学籍番号を入れてください
"""

student_number = 62101046

"""例題1: forループ

以下のrange内のXXXを適切に埋め、1~10まの間の奇数をすべて表示するプログラムを完成させよ
（ただし、if文は使わないものとする）
"""

for i in range(1, 10, 2):
  print(i)

"""例題2: エラー

- try, catchはエラー処理のための構文である。tryブロックで起きたエラーのうち、except句で指定されたタイプのエラーをexceptブロックで処理することができる。
- また、raiseはエラーを指定して発生させることができる命令である。


以上をもとに、以下のXXXを正しく埋めてエラー処理を完成させよ
"""

try:
  raise TypeError("型エラー発生")
except TypeError as e:
  print(e)

"""例題3: 文字列操作
以下のXXXに適切な式を埋め、最終的に`print(s)`によって"azbzcz"と出力されるようにせよ
"""

message = ""
for s in "abc":
  message += s
  message += "z"

print(message)



